ASSIGNMENT: DATA STRUCTURE

**Q:1. What are data structures and why are they important?**


Ans: A data structure is a way of organizing and storing data. There are some types of data structures are given here.
List
Tuple
String
Set
Data structures are extremely important in Python. Data Structures are fundamental for organizing, storing and efficiently manipulating data, that is crucial for operating applications.

**Q:2. Explain the difference between Mutable and Immutable data types with examples.**

Ans:  Mutable Data Types:- These are data types, whose value can be modified after they are created.
eg.: List, Set
     
  Immutable Data Types: These are data types, whose value can not be modified after they are created.
eg.: Tuple, String

**Q:3. What are the main differences between List and Tuples in python ?**

Ans:
Lists:
Lists are Mutable
List is defined using square brackets [ ].
        
Tuples:
Tuples are immutable
Tuple is defined using round brackets ( ).

**Q:4. Describe how dictionaries store data ?**

Ans: Dictionaries store data as unordered collections of Key-Value pairs. Where each key must be unique and Immutable, and values can be of any data type.
  
  eg:
   
      my_dict= {“name”: “vivek” , “age”: 30, “city”: “jaipur”}
      print(my_dict [“name”]) #output: Vivek


**Q:5. Why might you use a set instead of a list in python?**

Ans: Because sets cannot have multiple occurrences of same element. It makes set highly useful to efficiently remove duplicate values from a list.


**Q:6.  What is a string in Python, and how is it different from a list?**

Ans:
A string is a sequence of characters between single or double quotes and a list is a sequence of items, where each item could be anything (integer/float/string etc).
A string is immutable while a list is Mutable.

**Q:7.  How do tuples ensure data integrity in Python?**

Ans: Because Tuples are immutable, so we cannot modify or change the ordered or stored data in brackets. Therefore the stored data in tuples that are created once will never be modified, this property of tuples ensure data integrity in Python.

**Q:8. What is a hash table and how does it relate to dictionaries in Python?**

Ans: A hash table determines the position of a particular key that is stored in dictionaries.
  
  eg.
     
      dict1 = {"ronak": 17, "raveena": 20, "chetan": 30}
      print(dict1["raveena"])
       # Output: 20

**Q:9. Can lists Contain different data types in Python?**

Ans: Yes, lists in Python can contain different data types.

**Q:10. Explain why strings are immutable in Python?**

Ans: Immutability ensures that string values remain constant. Strings in python are immutable because of performance optimizations.


**Q:11. What advantages do dictionaries offer over lists for Certain tasks?**

Ans. Because dictionaries have fast lookup properties compared to lists.


**Q:12. Describe a scenario where using a tuple would be preferable over a list?**

Ans: When we need to store the collections of Adhar Number, ID no., mobile no., DOB etc, these are crucial data to have without any changes. So in these cases we can use tuple, because tuple is immutable and consequently can not modify or change.

**Q:13. How do sets handle duplicate values in Python?**

Ans: Sets in Python are designed to store only unique value. When attempting to add a duplicate value to a set, Python automatically ignores it, ensuring that the set maintains its uniqueness property.

**Q:14. How does the “in” keyword work differently for lists and dictionaries?**

Ans: List: “in” keyword checks it's membership in the list and give the output in Boolean

 Dictionaries: “in” checks the value of the exist key in given dictionary.

**Q:15 Can you modify the elements of a tuple? Explain why or why not.**

Ans: No we can not change or modify the elements of a tubke that is created once, because the tuples are Immutable.

**Q:16. What is a nested dictionary and give an example of its use case?**

Ans: A nested dictionary has stored multiple datasets.
    
    eg: to look up any data of an employee of a particular department from many employees of various departments of a company.

**Q:17. Describe the time Complexity of assessing elements in a dictionary?**

Ans: The time complexity to retriev a value in a dictionary is O(1). This is because dictionaries use a hash table which allows a definite time lookup.

**Q:18. In what situations are lists preferred over dictionaries?**

Ans: When data is crucial and need to have well arranged and sorted in a sequence.

**Q:19. Why are dictionaries Considered unordered, and how does that affect data retrieval?**

Ans: Dictionaries are considered unordered because they don't maintain a specific order of elements. This means data retrieval is based on keys, not positions.

**Q:20. Explain the difference between a list and a dictionary in terms of data retrieval.**

Ans: Lists access elements by their numerical index (starting from 0), while dictionaries access elements (values) by their unique key.

**Practical Questions:-**

In [ ]:
# Q:1. Write a code to create a string with your name and print it.

name = "vivek"
print(name)

vivek

In [ ]:
#Q:2. Write a code to find the length of the string “Hello World”
a = "Hello World"
len(a)

11

In [ ]:
# Q:3. Write a code to slice the first 3 Characters from the string “Python Programming”.

s = "Python Programming"
s1 = s[:3]
print(s1)

Pyt

In [ ]:
#Q:4. Write a code to Convert the string “hello” to uppercase.
s = "hello"
s1 = s.upper()
print(s1)

HELLO

In [ ]:
#Q:5. Write a code to replace the word “apple” with “orange” in the string “I like apple”.
string = "I like apple"
s1 = string.replace("apple", "orange")
print(s1)

I like orange

In [ ]:
  l = [1, 2, 3, 4, 5]
  print(type(l))
  print(l)
  l = list(range (1, 6))
  print(l)

<class 'list'>
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]

Write a code to append the number 10 to the list [1, 2, 3, 4]

In [ ]:

  list = [1, 2, 3, 4]
  list.append(10)
  list

[1, 2, 3, 4, 10]

Write a code to remove the number 3 from the list [1, 2, 3, 4, 5].

In [ ]:
list = [1, 2, 3, 4]
list.remove(3)
list

[1, 2, 4]

Write a code to access the second element in the list ['a', 'b', 'c', 'd']

In [ ]:
list = ['a', 'b', 'c', 'd']
second_element = list[1]
second_element

'b'

Write a code to reverse the list [10, 20, 30, 40, 50].

In [ ]:
list = [10, 20, 30, 40, 50]
list.reverse()
print(list)

[50, 40, 30, 20, 10]

Write a code to create a tuple with the elements 100, 200, 300 and print it.

In [ ]:
t = (100, 200, 300)
print(t)

(100, 200, 300)

Write a code to access the second-to-last element of the tuple ('red', 'green', 'blue', 'yellow').

In [ ]:
tuple = ('red', 'green', 'blue', 'yellow')
second_to_last_element = tuple[1:3]
second_to_last_element

('green', 'blue')

Write a code to find the minimum number in the tuple (10, 20, 5, 15).

In [ ]:
t = (10,20,5,15)
minimum_number = min(t)
minimum_number

5

Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit').

In [ ]:
t = ('dog', 'cat', 'rabbit')
index_of_cat = t.index('cat')
index_of_cat

1

Write a code to create a tuple containing three different fruits and check if "kiwi" is in it.

In [ ]:
fruits = ('apple', 'banana', 'kiwi')
if "kiwi" in fruits:
  print("Kiwi is in fruits")
else:
    print("kiwi is not in fruits")

Kiwi is in fruits

Write a code to create a set with the elements 'a', 'b', 'c' and print it.

In [ ]:
sets = {'a', 'b', 'c'}
sets

{'a', 'b', 'c'}

Write a code to clear all elements from the set {1, 2, 3, 4, 5}

In [ ]:
set = {1, 2, 3, 4, 5}
set.clear()
set

set()

Write a code to remove the element 4 from the set {1, 2, 3, 4}

In [ ]:
set = {1,2,3,4}
set.remove(4)
set

{1, 2, 3}

Write a code to find the union of two sets {1, 2, 3} and {3, 4, 5}

In [ ]:
s1 = {1,2,3}
s2 = {3,4,5}
s3 = s1.union(s2)
s3

{1, 2, 3, 4, 5}

Write a code to find the intersection of two sets {1, 2, 3} and {2, 3, 4}

In [ ]:
s1 = {1,2,3}
s2 = {3,4,5}
s3 = s1.intersection(s2)
s3

{3}

Write a code to create a dictionary with the keys "name", "age", and "city", and print it.

In [ ]:
dict1 = {
  "name": "vivek",
  "age": 30,
  "city": "jaipur"
}
dict1

{'name': 'vivek', 'age': 30, 'city': 'jaipur'}

Write a code to add a new key-value pair "country": "USA" to the dictionary {'name': 'John', 'age': 25}.

In [ ]:
d = {'name': 'John', 'age': 25}
d['country'] = 'USA'
d

{'name': 'John', 'age': 25, 'country': 'USA'}

Write a code to access the value associated with the key "name" in the dictionary {'name': 'Alice', 'age': 30}.

In [ ]:
d = {'name': 'Alice', 'age': 30}
value = d['name']
value

'Alice'

Write a code to remove the key "age" from the dictionary {'name': 'Bob', 'age': 22, 'city': 'New York'}.

In [ ]:
d = {'name': 'Bob', 'age': 22, 'city': 'New York'}
d1 = d.pop('age')
print(d)

{'name': 'Bob', 'city': 'New York'}

Write a code to check if the key "city" exists in the dictionary {'name': 'Alice', 'city': 'Paris'}.

In [ ]:
dictionary = {'name': 'Alice', 'city': 'Paris'}
if 'city' in dictionary:
  print("City exists")
else:
    print("city does not exist")

City exists

Write a code to create a list, a tuple, and a dictionary, and print them all.

In [ ]:
my_list = [1,2,3,4,5]
my_tuple = (1,2,3,4,5)
my_dictionary = {"name": "vivek","age": 30,"city": "jaipur"}
print(my_list)
print(my_tuple)
print(my_dictionary)

[1, 2, 3, 4, 5]
(1, 2, 3, 4, 5)
{'name': 'vivek', 'age': 30, 'city': 'jaipur'}

Write a code to create a list of 5 random numbers between 1 and 100, sort it in ascending order, and print the
result.(replaced)

In [ ]:
a = [10, 25, 91, 58, 37]
a.sort()
print(a)

[10, 25, 37, 58, 91]

Write a code to create a list with strings and print the element at the third index.

In [ ]:
my_list = ["rahul", "vivek", "ankit", "sanjesh", "vicky"]
element3 = my_list[2]
print(element3)

ankit

Write a code to combine two dictionaries into one and print the result.

In [ ]:
d1 = {'name':'alok', 'age':32, 'city':'nagaur'}
d2 = {'college':'pce', 'year':2015, 'place':'sikar'}
d3 = {**d1, **d2}
print(d3)

{'name': 'alok', 'age': 32, 'city': 'nagaur', 'college': 'pce', 'year': 2015, 'place': 'sikar'}

Write a code to convert a list of strings into a set.

In [ ]:
my_list = ["apple", "banana", "cherry"]
my_set = set(my_list)
print(my_set)

{'banana', 'cherry', 'apple'}